### ISSUE TITLE
chess-gang.herokuapp.com doesn't work

### ISSUE THREAD

**Issue by DmitriMedved** [kevinjoseph61/chess#1]
Please fix it

**Comment by kevinjoseph61** [comment]
Hi @DmitriMedved,
Heroku recently removed their free tiers so the hobby dyno I was using is down.
You can deploy it yourself with the instructions given and it should work
Let me know if need anything else

**Comment by kevinjoseph61** [comment]
Hi @DmitriMedved 
Render.com has something similar to Heroku. You can have a look at the new link I put up on the repo using that
